### ISSUE TITLE
Feature Request-Cover Stays Open

### ISSUE THREAD

**Issue by y0himba** [Fosmos/Simply#1]
Hello.

I've been using a combination of Clear Text and Monstercat Visualizer as seen in the screenshot.  Your skin makes that obsolete, if the cover can stay open. If the cover can stay open, the controls would need to fade in on mouseover.  Is there an edit I can make or can the option be added?

Also, I'd love to be able to change the text color to my desktop color.

It's a great skin, so easy and absolutely simple. Thanks!

(This is actually two skins as stated above)
![image](https://user-images.githubusercontent.com/11462603/150908254-57dc2afc-f489-43a4-a1f8-048d2ef39f88.png)

**Comment by Fosmos** [comment]
Here's a fun fact. I had the same setup as you (with the two visualizers) and decided to make a merged version.

I can add a toggle for "auto-hide album cover" fairly quickly, I think.

For the colors. Do you want it to be dynamic (i.e., it picks the color from your background automatically) or would you rather set the color manually?

**Comment by y0himba** [comment]
> Here's a fun fact. I had the same setup as you (with the two visualizers) and decided to make a merged version.
> 
> I can add a toggle for "auto-hide album cover" fairly quickly, I think.
> 
> For the colors. Do you want it to be dynamic (i.e., it picks the color from your background automatically) or would you rather set the color manually?

Thanks for the reply!  I think it would be better to have both, since not everyone is going to want or be able to set a color. I prefer setting my own color since I like a very specific color, but chameleon might get it right from my desktop. 

I found this through the Spicetify Github discussions. It's perfect, and I don't see why more folks aren't over here bugging you for stuff like me. :)

**Comment by Fosmos** [comment]
Just as an update.

I've:
- Setup the auto-hide toggle. Cleaned up the backend.
- Lowered the GPU usaged from ~4-6% down to 0.1%-4% (on my system anyway). 
- I've got a very basic custom color picker throught the settings

What's next:
- Add color picking for virtually everything while still keeping the settings window fairly simple and small
- Add better control over the chameleon colors

**Comment by y0himba** [comment]
I appreciate this!

**Comment by Fosmos** [comment]
All Done! Check the [latest](https://github.com/Fosmos/Simply/releases/tag/v1.30) release
